### ISSUE TITLE
Enabling solo play?

### ISSUE THREAD

**Issue by Betterzenmama** [dguzek/Simply-Love-SM5#25]
This one is less of a bug and more a request. Can Simply Love get an option for enabling Solo (6-panel) play? Solo mode is enabled in the default Stepmania theme, but seems to be disabled in Simply Love. Is there a way to turn that on or implement that in this theme?

Thanks!

**Comment by dguzek** [comment]
I'm not familiar with any 6-panel game types in StepMania.  That I know of, there are:

* dance (4-panel)
* pump (5-panel)
* techno (4, 5, or 8-panel)
* kb7 (7-panel)
* popn (9-panel)
* beat (7-panel)
* kickbox (not sure)

In this theme, you can switch between available gametypes in *System Options* in the main Service menu.  Is this what you mean?

**Comment by Betterzenmama** [comment]
DDR Solo machines were actually 6 panel setups (http://upload.wikimedia.org/wikipedia/commons/e/e5/Dance_Dance_Revolution_Solo_2000_arcade_machine.jpg) in the config files (noteskins) that you listed, under 'dance' there is a note for either 4 or 6 panel charts.  Stepmania can play 6-panel charts in the default theme, after selecting 'dance', it'll then specify charts/marathon/etc, but one of those options is 'solo' which enables 6-panel charts.

In system options I can change overall game modes, but if I select 'dance' it disables solo play.

Not explicitly a problem, just hoping all my fanboy needs can be met :P love the theme!

**Comment by kyzentun** [comment]
Solo is actually one of the possible styles for the dance game type.  All you have to do is add it to your ScreenSelectStyle as a choice, then figure out how to hide it on arcade machines.  I sent Betterzenmama here because I figured you could easily add it as a choice.

**Comment by dguzek** [comment]
This issue should be resolved by the most recent commit, 16a0458ebf057c83e2d6710c0e4c90cf9da9ad22

Using this feature in Simply Love requires a nightly build of StepMania 5 for now (5.0.7 is not new enough).  Also, due to an easy-to-trigger crash I found, it may just be best to wait for StepMania 5.0.8.

I'm closing this issue now.  Feel free to reopen it if you do not feel it has been fixed or if you find some problem with it.

**Comment by kyzentun** [comment]
I think I've fixed the crash where one player is on solo and the other player joins, but I feel like someone is going to find an unexpected side effect problem the fix causes.  Now if there isn't a style for two players with the same stepstype, the second player can't join.  Maybe this fixes the two players in popn crash too.  https://github.com/stepmania/stepmania/commit/236947b346875966e81d1dc70e1ab5af867fd0b0

**Comment by Betterzenmama** [comment]
Are these fixes only for linux/Cmake? I've got the most recent commit of Simply Love and the most recent (907) nightly from smnightly, and still cannot select a style. I use linux builds elsewhere, but for this particular project, stepmania has to be run in a windows environment. 

Also, do either of you know about Serial control with stepmania? I know that used to be a feature back in the 3.95 days, but I was looking to get that back, so i've been working on my own.

**Comment by dguzek** [comment]
@Betterzenmama, I apologize for not being especially clear about it.

Solo gameplay can be enabled within *Simply Love Options* in the general Operator Menu.  Once enabled, it will appear as a selectable style on ScreenSelectStyle in "dance" game mode.

Hopefully this works for you.

I am not familiar with "Serial control" in StepMania; I have actually never heard of it.

**Comment by dguzek** [comment]
Also, to further clarify, it appears that nightly build  907 does **not** includes @kyzentun's recent fixes to the engine that fixed the late-join crash.  I can't really comment on why a newer nightly build isn't available; I don't use Windows, myself.

**Comment by Betterzenmama** [comment]
Oh rad! I thought it would be after the 'dance' selection similar to the SM5 default theme.

No worries, I can wait it out, my other machine is debian, but I'm playing around with windows-specific network libraries and hardware controllers for an expanded serial-out controller type.
